root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
args_bin = []
bin = "./tmp/main"
cmd = "go run github.com/a-h/templ/cmd/templ@latest generate && go build -o ./tmp/main ./cmd/api"
delay = 1000
exclude_dir = [
  ".parcel-cache",
  "bin",
  "dist",
  "node_modules",
  "./cmd/api/http/view/static",
  "tmp",
  "tests",
  "vendor",
  "./cmd/api/http/view/assets",
  "testdata",
]
exclude_file = []
exclude_regex = ["_test.go", "_templ\\.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = [
  "go",
  "tpl",
  "tmpl",
  "templ",
  "html",
  "json",
  "js",
  "ts",
  "css",
  "scss",
]
include_file = []
kill_delay = "0s"
log = "build-errors.log"
poll = false
poll_interval = 0
post_cmd = []
pre_cmd = ["bun run build"]
rerun = false
rerun_delay = 500
send_interrupt = false
stop_on_error = false

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = false

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
keep_scroll = true
