version: '3.8'

services:
#  mooc-app-services-go:
#    build: .
#    environment:
#      MOOC_HOST: 0.0.0.0
#      MOOC_DBHOST: mysql
#    ports:
#      - 8080:8080

  mysql:
    image: mysql:8.0.22
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: example
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
  rabbitmq:
    image: 'rabbitmq:3.8-management'
    ports:
      - "5672:5672"
      - "15672:15672"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
volumes:
  mysql_data: