CREATE TABLE IF NOT EXISTS courses (
  id VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  duration VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  validated BOOLEAN NOT NULL DEFAULT FALSE,
  PRIMARY KEY (id)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;